### ISSUE TITLE
No USB devices work in VM

### ISSUE THREAD

**Issue by ElijahZAwesome** [joeknock90/Single-GPU-Passthrough#17]
I'm trying to use this with a macOS VM, and I pretty much followed the steps to a T (I had to dick around with he gitlab scripts and some other stuff but it's more or less a normal setup) but now when I finally boot into the VM, my keyboard and mouse don't work, either in clover or in actual macOS (using clovers "defaultdisk" property or whatever its called). It used to work in libvirt (before using this guide), it works in basic.sh, but not with this passthrough method. My *only* guess is maybe it's because I enabled iommu=pt in grub but I really doubt that. If anyone knows why this is happening I would appreciate an explanation.

**Comment by ElijahZAwesome** [comment]
It also might have something to do with having disabled the Spice server... Going out on a whim

**Comment by McAndze** [comment]
I never got mine to work in Clover, and had to use virsh console on another machine to navigate that menu. I think you can install some kexts to fix that though. If you're passing through an entire USB controller, there is a chance it's not supported by macOS. Passing through individual USB devices works for me using the emulated controllers in the XML from macOS-Simple-KVM, but not well enough for e.g. USB sound cards to work properly.

**Comment by luuisAfonso** [comment]
Now it's a little bit to late to awnser this question, but I think I know one way to make your usb devices works in the VM. Days ago I ran into the same problem and solved it by using evdev passthrough usb. You are probably using qemu, so it's should works just fine. 

The article that I found very helpful was this one: https://passthroughpo.st/using-evdev-passthrough-seamless-vm-input 

If you are not using the Virtual Manganer Gui to boot up your VM, you could just append the "-object PATH-TO-DEVICE-ID \" at the end of you baisc.sh.

I hope it's turns out to be helpful.
