### ISSUE TITLE
What do you exactly mean by "logged out of your user on the host"?

### ISSUE THREAD

**Issue by tberghuis** [joeknock90/Single-GPU-Passthrough#20]
Do you mean that all your running programs will be shutdown on the host to run the guest, or that only can't use running programs on the host until you finish using the guest?

I would like that you can return to the host without all open programs being lost.

**Comment by joeknock90** [comment]
To bind the GPU to the guest, you need to kill the display manager. Any GUI app you were running will be closed while you use the VM.

Now, in my startup script, I have it start a VNC server, just in case I want to do any manipulation on the host while running the guest. You could also still SSH into the guest.

You CAN keep user systemd services running by enabling linger.

To your question, with single GPU passthrough keeping running applications open is simply impossible with the current implementation of X11. I would assume the case is the same for Wayland. I don't know if will ever be possible honestly because you are disconnecting the GPU that all of the applications are currently using. That would be one of the limitations of Single GPU Passthrough.

**Comment by tberghuis** [comment]
Thanks for the detailed answer
