### ISSUE TITLE
Can not unbind GPU, command hangs

### ISSUE THREAD

**Issue by sandrokeil** [joeknock90/Single-GPU-Passthrough#6]
Thank you very much for this guide. I've followed the guide and configured a Win10 VM with UEFI and own NVIDIA ROM for GTX 1080 TI. I use latest Arch Linux with QEMU and Libvirt.

The script hangs on unbinding my GPU `echo -n "0000:42:00.0" > /sys/bus/pci/drivers/nvidia/unbind`. I've tested it via SSH and I get no response of this command, it still hangs. 

Have you any tips for debugging or what I can do? Here some debug info.

```
$ lspci -nn | grep -i nvidia
42:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] [10de:1b06] (rev a1)
42:00.1 Audio device [0403]: NVIDIA Corporation GP102 HDMI Audio Controller [10de:10ef] (rev a1)
```

```
$ dmesg | grep efifb
[    1.385642] pci 0000:42:00.0: BAR 3: assigned to efifb
[    1.720433] efifb: probing for efifb
[    1.720445] efifb: No BGRT, not showing boot graphics
[    1.720445] efifb: framebuffer at 0x91000000, using 5120k, total 5120k
[    1.720446] efifb: mode is 1280x1024x32, linelength=5120, pages=1
[    1.720446] efifb: scrolling: redraw
[    1.720447] efifb: Truecolor: size=8:8:8:8, shift=24:16:8:0

```

**Comment by joeknock90** [comment]
Sorry to get back late. I'm changing a few things I read from Yuri's guide. 

Instead of echoing the PCI device ID to unbind the driver, you can try the following. So far it has given me more consistent results in unbinding:

`virsh nodedev-detatch PCI_0000_42_00_0`

should be the alternative command. 

I also had a problem with unbinding after stopping GDM because for some reason, GDM remains running on VT1 after stopping. I'm not sure why. 

If neither of these works, it might be worth disabling the EFI-framebuffer at boot in the kernel commandline.

**Comment by sandrokeil** [comment]
Thanks for your response. As [mentioned here](https://gitlab.com/YuriAlek/vfio/issues/3#note_127921719), maybe I should not load `MODULES=(ext4 nvidia nvidia_modeset nvidia_uvm nvidia_drm)` at boot. But at the moment I don't have time to test it.

**Comment by joeknock90** [comment]
You shouldn't have to load any modules for nvidia in mkinitcpio. I would definitely try taking those out, regenerating mkinitcpio and see what happens there. 

Let me know.
